sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

cache:
  directories:
    - ~/.composer/cache

before_install:
  - composer self-update

install:
  - composer update --prefer-source

script:
  - cd test && ../vendor/bin/phpunit --coverage-clover ../clover.xml
  - ./vendor/bin/phpcs

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
